FROM node:16-alpine

WORKDIR /usr/react-app

COPY package.json .

RUN npm install

RUN mkdir -p /usr/react-app/node_modules/.cache && chmod -R 777 /usr/react-app/node_modules/.cache

COPY . .

CMD ["npm", "run", "start"]
