version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - /usr/react-app/node_modules
      - .:/usr/react-app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/react-app/node_modules
      - .:/usr/react-app
    command: ["npm", "run", "test"]
